apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
rules:
- apiGroups: [""] 
  resources: ["pods", "deployments", "secrets", "services", "jobs", "nodes", "configmaps", "endpoints"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
