apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: admin-rolebinding
  namespace: default
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin-role # this must match the name of the Role or ClusterRole you wish to bind tos
  apiGroup: rbac.authorization.k8s.io