apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: developer-rolebinding
  namespace: default
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role # this must match the name of the Role or ClusterRole you wish to bind tos
  apiGroup: rbac.authorization.k8s.io