apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]

---


  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: admin
  rules:
  - apiGroups: [""] 
    resources: ["pods", "deployments", "secrets", "services", "statefulsets", "jobs", "nodes", "configmaps", "endpoints"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
