apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: shreyas
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-role # this must match the name of the Role or ClusterRole you wish to bind tos
  apiGroup: rbac.authorization.k8s.io