namespace: default

replicaCount: 3
frontendImage: localhost:32000/inventory-ui:v1
frontendTargetPort: 80
frontendPort: 8888
backendImage: localhost:32000/inventory-api:v1
backendTargetPort: 5000
backendPort: 8081
dbPort: 5432
hostName: movies.com