apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.targetPort }}
      nodePort: {{ .Values.api.nodePort }}
  selector:
    app: {{ .Release.Name }}-backend