apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.app }}
  namespace: {{ .Values.namespace }}
  labels:
    type: {{ .Values.db.storage.type }}
    app: {{ .Values.db.storage.appName }}
spec:
  storageClassName: {{ .Values.db.storage.storageClassName }}
  capacity:
    storage: {{ .Values.db.storage.capacity }}
  accessModes:
    - {{ .Values.db.storage.accessModes }}
  hostPath:
    path: {{ .Values.db.storage.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.storage.appName }}
spec:
  storageClassName: {{ .Values.db.storage.storageClassName }}
  accessModes:
  - {{ .Values.db.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.db.storage.capacity }}
