apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.config.appName }}
data:
  POSTGRES_DB: {{ .Values.db.config.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.db.config.POSTGRES_USER }}
  POSTGRES_PORT: {{ .Values.db.config.POSTGRES_PORT | quote }}
  POSTGRES_HOST: {{ .Values.db.config.POSTGRES_HOST }}
