
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.service.appName }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      nodePort: {{ .Values.db.service.nodePort }}
  selector:
    app: {{ .Values.db.service.appName }}